name: gitartwork from a contribution graph
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

permissions:
  contents: write

jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jasineri/gitartwork@v1
        with:
          # Use this username's contribution graph
          user_name: awnion
          # Text on contribution graph
          text: awnion
      - name: Clean artwork
        run: |
          sed -i 's/<a[^>]*>.*<\/a>//g' ./gitartwork.svg
      - name: Commit files
        run: |
          git config user.name "Sergei Blinov"
          git config user.email "<blinovsv@gmail.com>"
          git add .
          git diff-index --quiet HEAD || git commit -m "update action output" && git push
        shell: bash
